### ISSUE TITLE
Is a coverflow with looping option available?

### ISSUE THREAD

**Issue by hishhash2** [drien/jquery-flipster#64]
If i have 3 items, i always want the clicked image on the center & 1 item on each side. Currently i am using 'carousel' style & when i am on the last item there is 2 items on the left & none on the right. So i need a looping style. ????

**Comment by shshaw** [comment]
For three items, this can be faked with CSS by adapting the carousel styles, but isn't directly supported by an option within Flipster.

The styles would be something like this:

```css
    .flipster__item--future-2 .flipster__item__content,
    .flipster__item--past .flipster__item__content { 
      transform: translateX(100%) rotateY(-20deg) scale(0.5);
    }
```
